# Generated by Django 3.2 on 2022-05-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220505_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmworkgenre',
            name='film_work',
            field=models.ForeignKey(db_column='film_work_id', on_delete=django.db.models.deletion.CASCADE, related_name='genres_film_work', to='movies.filmwork', verbose_name='film_work'),
        ),
        migrations.AlterField(
            model_name='filmworkgenre',
            name='genre',
            field=models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, related_name='genres_film_work', to='movies.genre', verbose_name='genre'),
        ),
    ]
